# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fastai.github.io/kaggle_1c_predict_future_sales/"

git_url = "https://github.com/fastai/kaggle_1c_predict_future_sales/tree/master/"

def custom_doc_links(name): return None
